/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f3f0f4',
        'primary-fixed': '#ffd9e4',
        'on-secondary-fixed-variant': '#6e3900',
        'on-tertiary-fixed-variant': '#46464e',
        'surface-tint': '#9c3c66',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        tertiary: '#171820',
        surface: '#fbf8fc',
        'secondary-fixed': '#ffdcc3',
        error: '#ba1a1a',
        'tertiary-fixed': '#e3e1ec',
        'on-error': '#ffffff',
        'surface-container-high': '#eae7eb',
        'secondary-container': '#fe932c',
        'tertiary-fixed-dim': '#c6c5cf',
        'surface-variant': '#e4e1e6',
        'tertiary-container': '#2c2d35',
        'error-container': '#ffdad6',
        secondary: '#904d00',
        'on-background': '#1b1b1e',
        outline: '#867278',
        'on-tertiary-container': '#94949d',
        'on-secondary': '#ffffff',
        'outline-variant': '#d9c0c7',
        'primary-fixed-dim': '#ffb0cc',
        'primary-container': '#5c0534',
        'on-primary-container': '#de719d',
        'inverse-primary': '#ffb0cc',
        'surface-container-lowest': '#ffffff',
        primary: '#38001d',
        'surface-container-low': '#f6f2f7',
        'on-primary-fixed-variant': '#7e244e',
        background: '#fbf8fc',
        'surface-dim': '#dcd9dd',
        'secondary-fixed-dim': '#ffb77d',
        'surface-container-highest': '#e4e1e6',
        'surface-container': '#f0edf1',
        'surface-bright': '#fbf8fc',
        'on-surface': '#1b1b1e',
        'on-secondary-fixed': '#2f1500',
        'inverse-surface': '#303033',
        'on-secondary-container': '#663500',
        'on-surface-variant': '#544248',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#1a1b22',
        'on-primary-fixed': '#3e0021',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        gutter: '1rem',
        'space-md': '1rem',
        'margin-desktop': '3rem',
        'margin-tablet': '2rem',
        'gutter-tablet': '1.5rem',
        'space-2xl': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        margin: '1rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'label-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-md': ['Newsreader'],
        'label-sm': ['Plus Jakarta Sans'],
        'headline-lg': ['Newsreader'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        display: ['Newsreader'],
        'headline-lg-mobile': ['Newsreader'],
        'headline-sm': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['0.875rem', { lineHeight: '1.4rem', fontWeight: '400' }],
        'headline-md': ['1.375rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.06em', fontWeight: '700' }],
        'headline-lg': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.015em', fontWeight: '500' }],
        'body-sm': ['0.75rem', { lineHeight: '1.125rem', fontWeight: '400' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.6rem', fontWeight: '400' }],
        display: ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.5rem', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
